name: "Medicines App"
description: "Medicines App"
version: "1.0.0"
slug: "medicines"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
homeassistant_api: true
ports:
  8100/tcp: 8100
options:
  datasource_url: 
  datasource_username: 
  datasource_pwd: 
schema:
  datasource_url: str
  datasource_username: str
  datasource_pwd: password
ingress: true
ingress_port: 8100
